export const BANCOS = [
  "BBVA México",
  "Santander",
  "Citibanamex",
  "Banorte",
  "HSBC",
  "Scotiabank",
  "Inbursa",
  "Banco Azteca",
  "Afirme",
  "Banregio",
  "BanBajío",
  "Invex",
  "Mifel",
  "Actinver",
  "Intercam",
  "Banjercito",
  "Banco del Bienestar",
  "Nu (Nubank)",
  "Mercado Pago",
  "Klar",
  // Fintech / tiendas
  "Saldazo (OXXO)",
  "Spin by OXXO",
  "Spin Premia",
  "BanCoppel",
  "Hey Banco",
  "Ualá",
  "STP",
  "CIBanco",
  "Banca Mifel",
  "Multiva",
  "Compartamos Banco",
  "Banco Sabadell",
  "Banco Famsa",
  "RappiPay",
  "Stori",
  "Cuenca",
  "Albo",
  "Fondeadora",
  "Somos",
].sort((a, b) => a.localeCompare(b, "es"));

export const MONEDAS = [
  { value: "MXN", label: "MXN - Peso Mexicano" },
  { value: "USD", label: "USD - Dólar" },
  { value: "EUR", label: "EUR - Euro" },
];
